/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tezbozor API
 * Next-day grocery delivery — backend API (contract owner).
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from './fetcher';
export interface HealthResponseDto {
  status: string;
  /** Seconds since the process booted */
  uptimeSeconds: number;
  /** Server time (UTC, ISO 8601) */
  timestamp: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type healthControllerCheckResponse200 = {
  data: HealthResponseDto
  status: 200
}
    
export type healthControllerCheckResponseSuccess = (healthControllerCheckResponse200) & {
  headers: Headers;
};
;

export type healthControllerCheckResponse = (healthControllerCheckResponseSuccess)

export const getHealthControllerCheckUrl = () => {


  

  return `/api/health`
}

export const healthControllerCheck = async ( options?: RequestInit): Promise<healthControllerCheckResponse> => {
  
  return customFetch<healthControllerCheckResponse>(getHealthControllerCheckUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getHealthControllerCheckQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }

    
export const getHealthControllerCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerCheck>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerCheck>>> = ({ signal }) => healthControllerCheck({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthControllerCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerCheck>>>
export type HealthControllerCheckQueryError = unknown



export function useHealthControllerCheck<TData = Awaited<ReturnType<typeof healthControllerCheck>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthControllerCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
